name: my_budget
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.4
  cloud_functions: ^4.0.7
  dio: ^5.3.2
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  get_it: ^7.6.0
  google_sign_in: ^5.2.2
  hooks_riverpod: ^2.3.3
  intl: ^0.18.1
  shared_preferences: ^2.0.12
  stacked_services: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # - .env
    - assets/images/
