name: my_budget
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  dio: ^5.3.2
  equatable: ^2.0.5
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  intl: ^0.18.1
  stacked_services: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
